dist: trusty

addons:
  sonarcloud:
    organization: "sanogotech"
    token:
      secure: "5620efd93d4938aa61c8343af0339153d3f817de" # encrypted value of your token

install: composer install --prefer-dist

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - vendor/bin/phpunit  --coverage-clover=coverage-report.clover --log-junit=test-report.xml
  - sonar-scanner
